server:
  port: 8066

#Eureka配置
eureka:
  instance:
    hostname: eureka8066.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url:
     # 单机： defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
     # 集群（关联）：
      defaultZone: http://eureka8067.com:8067/eureka/,http://eureka8068.com:8068/eureka/